
services:
  wyx2685:
    container_name: wyx2685
    build: .
    volumes:
      - ./supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./httpd.conf:/etc/nginx/http.d/default.conf
      - ./data:/data
      - ./data/config.env:/www/.env
      - ./data/config.php:/www/config/v2board.php
    environment:
      - docker=true
    restart: always
    ports:
      - 127.0.0.1:49992:80
    networks:
      - 1panel-network

networks:
    1panel-network:
        external: true

